/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.http"))
    api(project(":basyx.aasdiscoveryservice-core"))
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.json)
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasdiscoveryservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasdiscoveryservice-backend-mongodb"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
    testImplementation(libs.commons.io.commons.io)
}

description = "AAS Discovery Service HTTP"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
