/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasrepository.component"))
    api(project(":basyx.submodelrepository.component"))
    api(project(":basyx.conceptdescriptionrepository.component"))
    api(project(":basyx.core"))
    api(project(":basyx.submodelrepository-backend-inmemory"))
    api(project(":basyx.submodelservice-backend-inmemory"))
    api(project(":basyx.aasservice-backend-inmemory"))
    api(project(":basyx.conceptdescriptionrepository-backend-inmemory"))
    api(project(":basyx.aasrepository-backend-inmemory"))
    api(project(":basyx.submodelrepository-core"))
    api(project(":basyx.aasrepository-core"))
    api(project(":basyx.conceptdescriptionrepository-core"))
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.json)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.xml)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.aasx)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.core)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.model)
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.org.slf4j.slf4j.api)
    api(libs.com.google.guava.guava)
    api(libs.org.apache.poi.poi.ooxml)
    api(libs.org.springframework.integration.spring.integration.file)
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
    testImplementation(libs.org.mockito.mockito.core)
}

description = "BaSyx AAS Environment Core"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
