/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.submodelservice-backend-inmemory"))
    api(project(":basyx.submodelservice-http"))
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
    testImplementation(libs.commons.io.commons.io)
}

description = "BaSyx submodelservice.example"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
