/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.tomcat)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    api(libs.org.projectlombok.lombok)
compileOnly("org.projectlombok:lombok:1.18.20")
annotationProcessor("org.projectlombok:lombok:1.18.20")
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.com.google.guava.guava)
    api(libs.org.openapitools.jackson.databind.nullable)
    api(project(":basyx.core"))
    api(project(":basyx.http"))
    api(libs.org.junit.vintage.junit.vintage.engine)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.apache.commons.commons.lang3)
    compileOnly(project(":basyx.submodelregistry-service-basemodel"))

}

description = "BaSyx Submodel Registry Service"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
