/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.mongodbcore"))
    api(project(":basyx.conceptdescriptionrepository-core"))
    api(project(":basyx.conceptdescriptionrepository-backend-inmemory"))
    api(project(":basyx.conceptdescriptionrepository-backend-mongodb"))
    api(project(":basyx.conceptdescriptionrepository-feature-authorization"))
    api(project(":basyx.conceptdescriptionrepository-http"))
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(project(":basyx.authorization"))
    testImplementation(project( path =":basyx.conceptdescriptionrepository-feature-authorization", configuration = "testArtifacts"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(project( path =":basyx.conceptdescriptionrepository-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.conceptdescriptionrepository-http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.conceptdescriptionrepository-tck", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
    testImplementation(libs.commons.io.commons.io)
    testImplementation(libs.com.google.code.gson.gson)
}

description = "Concept Description Repository Component"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
