/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.json)
    api(libs.org.eclipse.paho.org.eclipse.paho.client.mqttv3)
    api(libs.io.moquette.moquette.broker)
}

description = "BaSyx mqtt core"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
