/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasrepository-core"))
    api(project(":basyx.aasrepository-backend"))
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.boot.spring.boot.starter)
    api(project(":basyx.filerepository-backend-inmemory"))
    testImplementation(project( path =":basyx.aasrepository-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasservice-backend-inmemory", configuration = "testArtifacts"))
}

description = "BaSyx AAS Repository backend-inmemory"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
