/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.submodelregistry-service"))
    api(project(":basyx.submodelregistry-service-basemodel"))
    api(libs.org.projectlombok.lombok)
compileOnly("org.projectlombok:lombok:1.18.20")
annotationProcessor("org.projectlombok:lombok:1.18.20")
    testImplementation(project( path =":basyx.submodelregistry-service-basetests", configuration = "testArtifacts"))
    compileOnly(project(":basyx.submodelregistry-service-basemodel", configuration = "testArtifacts"))
}

description = "BaSyx Submodel Registry Service Inmemory Storage"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
