/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasregistry-paths"))
    api(project(":basyx.aasregistry-client-native"))
    api(project(":basyx.aasregistry-service"))
    api(libs.org.springframework.boot.spring.boot.starter.test)
    api(project(":basyx.authorization"))
    api(project(":basyx.authorization"))
    api(project(":basyx.http"))
    api(libs.org.apache.httpcomponents.client5.httpclient5)
    api(libs.org.junit.vintage.junit.vintage.engine)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(project(":basyx.aasregistry-service-basemodel"))
}

description = "BaSyx AAS Registry Service Basetests"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
