/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasrepository-core"))
    api(project(":basyx.mqttcore"))
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.json)
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.eclipse.paho.org.eclipse.paho.client.mqttv3)
    testImplementation(project( path =":basyx.aasrepository-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasrepository-backend-inmemory", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasservice-backend-inmemory", configuration = "testArtifacts"))
    testImplementation(libs.io.moquette.moquette.broker)
}

description = "BaSyx AAS Repository feature-mqtt"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
