/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasrepository-http"))
    api(project(":basyx.http"))
    api(libs.org.apache.httpcomponents.client5.httpclient5)
    api(libs.commons.io.commons.io)
    api(libs.com.google.code.gson.gson)
}

description = "BaSyx AAS Repository TCK"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
