/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.http"))
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.org.openapitools.jackson.databind.nullable)
    api(libs.com.google.code.findbugs.jsr305)
    api(libs.org.apache.httpcomponents.httpmime)
    api(libs.org.json.json)
    api(libs.com.nimbusds.oauth2.oidc.sdk)
    compileOnly(libs.jakarta.annotation.jakarta.annotation.api)
}

description = "BaSyx Client Base"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
