/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasenvironment-core"))
    api(project(":basyx.aasenvironment-http"))
    api(project(":basyx.aasenvironment-feature-authorization"))
    api(project(":basyx.http"))
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.xml)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.aasx)
    api(libs.org.xmlunit.xmlunit.core)
    api(libs.org.xmlunit.xmlunit.matchers)
    testImplementation(project( path =":basyx.aasrepository.component", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasrepository-tck", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository.component", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-tck", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.conceptdescriptionrepository-tck", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.conceptdescriptionrepository.component", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
}

description = "BaSyx AAS Environment Component"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
