/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.model)
    api(libs.org.eclipse.digitaltwin.aas4j.aas4j.dataformat.json)
    api(project(":basyx.submodelrepository-core"))
    api(project(":basyx.client"))
    api(project(":basyx.submodelservice-client"))
    api(project(":basyx.authorization"))
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-client", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-backend-inmemory", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-backend-inmemory", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.authorization", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
    testImplementation(project( path =":basyx.submodelrepository-feature-authorization", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-feature-authorization", configuration = "testArtifacts"))
    testImplementation(libs.org.mockito.mockito.core)
}

description = "BaSyx SubmodelRepository Client"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
