/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.submodelregistry-client-native"))
    api(project(":basyx.submodelregistry-service"))
    api(libs.org.springframework.boot.spring.boot.starter.test)
    api(libs.org.junit.vintage.junit.vintage.engine)
    api(project(":basyx.authorization"))
    api(project(path = ":basyx.authorization", configuration = "testArtifacts"))
    api(project(path = ":basyx.http", configuration = "testArtifacts"))
    api(libs.org.apache.httpcomponents.client5.httpclient5)
    compileOnly(libs.org.projectlombok.lombok)
    compileOnly(project(":basyx.submodelregistry-service-basemodel"))
    compileOnly("org.projectlombok:lombok:1.18.20")
    annotationProcessor("org.projectlombok:lombok:1.18.20")
}

description = "BaSyx Submodel Registry Service Basetests"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
