/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.tomcat)
    api(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    api(libs.org.springframework.cloud.spring.cloud.function.context)
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.com.google.guava.guava)
    api(project(":basyx.submodelregistry-service"))
    api(libs.org.projectlombok.lombok)
    testImplementation(project( path =":basyx.submodelregistry-service-basetests", configuration = "testArtifacts"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.apache.commons.commons.lang3)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
}

description = "BaSyx Submodel Registry Service Mongodb Storage"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
