/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.submodelrepository-core"))
    api(project(":basyx.submodelservice-backend-inmemory"))
    api(project(":basyx.submodelrepository-backend-inmemory"))
    api(project(":basyx.submodelrepository-backend-mongodb"))
    api(project(":basyx.submodelrepository-feature-mqtt"))
    api(project(":basyx.submodelrepository-feature-registry-integration"))
    api(project(":basyx.submodelrepository-feature-authorization"))
    api(project(":basyx.submodelrepository-feature-operation-delegation"))
    api(project(":basyx.submodelrepository-http"))
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.commons.io.commons.io)
    api(project(":basyx.authorization"))
    testImplementation(project( path =":basyx.submodelrepository-feature-registry-integration", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-feature-authorization", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-feature-operation-delegation", configuration = "testArtifacts"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-tck", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
    testImplementation(libs.com.google.code.gson.gson)
}

description = "BaSyx submodelrepository.component"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
