/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasenvironment-core"))
    api(project(":basyx.http"))
    api(project(":basyx.authorization"))
    api(libs.org.springframework.spring.context)
    api(project(":basyx.aasenvironment-http"))
    api(libs.commons.io.commons.io)
    testImplementation(project( path =":basyx.aasenvironment-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.authorization", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.aasenvironment-http", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
}

description = "BaSyx AAS Environment feature-authorization"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
