/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.aasregistry-feature-authorization"))
    api(project(":basyx.authorization"))
    api(project(":basyx.aasregistry-service-basemodel"))
    api(project(":basyx.aasregistry-service"))
    api(project(":basyx.aasregistry-service-inmemory-storage"))
    api(libs.org.apache.commons.commons.lang3)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(project( path =":basyx.aasregistry-service-basetests", configuration = "testArtifacts"))
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "BaSyx AAS Registry Service Release Log Mem"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
