/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.submodelregistry-client-native"))
    api(project(":basyx.submodelrepository-core"))
    api(project(":basyx.http"))
    testImplementation(project( path =":basyx.http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-http", configuration = "testArtifacts"))
    testImplementation(libs.org.apache.httpcomponents.client5.httpclient5)
    testImplementation(project( path =":basyx.filerepository-backend-inmemory", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-http", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-backend-inmemory", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelrepository-backend-inmemory", configuration = "testArtifacts"))
}

description = "BaSyx Submodelrepository feature-registry-integration"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
