/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":basyx.submodelrepository-core"))
    api(project(":basyx.submodelrepository-backend"))
    api(project(":basyx.submodelservice-backend-inmemory"))
    api(project(":basyx.mongodbcore"))
    api(project(":basyx.submodelservice-core"))
    api(libs.org.apache.tika.tika.core)
    api(project(":basyx.filerepository-backend-mongodb"))
    testImplementation(project( path =":basyx.submodelrepository-core", configuration = "testArtifacts"))
    testImplementation(project( path =":basyx.submodelservice-core", configuration = "testArtifacts"))
}

description = "BaSyx submodelrepository-backend-mongodb"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
