/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.yaml.snakeyaml)
    api(libs.org.apache.maven.maven.plugin.api)
    api(libs.org.apache.maven.plugin.tools.maven.plugin.annotations)
    api(libs.org.apache.maven.maven.project)
    api(libs.com.github.spullara.mustache.java.compiler)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.org.projectlombok.lombok)
}

description = "BaSyx AAS Registry Plugins"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}
configurations {
    create("testArtifacts") {
        extendsFrom(testRuntimeClasspath.get())
    }
}
artifacts {
    add("testArtifacts", testsJar)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

java {
    withJavadocJar()
}
