name: Build and Test BaSyx

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CODING_CONVENTIONS.md'
      - '.github/CONTRIBUTING.md'
      - '.github/dependabot.yml'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'NOTICE'

env:
  MVN_ARGS_BUILD_BASYX_NO_TESTS: -DskipTests -T1C

jobs:
  test-basyx-aasenvironment:
    runs-on: ubuntu-latest
    name: Test BaSyx AAS Environment
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test AAS Environment
        run: mvn test -f "basyx.aasenvironment/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-aasrepository:
    runs-on: ubuntu-latest
    name: Test BaSyx AAS Repository
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test AAS Repository
        run: mvn test -f "basyx.aasrepository/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-aasservice:
    runs-on: ubuntu-latest
    name: Test BaSyx AAS Service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test AAS Service
        run: mvn test -f "basyx.aasservice/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-submodelrepository:
    runs-on: ubuntu-latest
    name: Test BaSyx Submodel Repository
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test Submodel Repository
        run: mvn test -f "basyx.submodelrepository/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-submodelservice:
    runs-on: ubuntu-latest
    name: Test BaSyx Submodel Service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test Submodel Service
        run: mvn test -f "basyx.submodelservice/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-conceptdescriptionrepository:
    runs-on: ubuntu-latest
    name: Test BaSyx Concept Description Repository
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test Concept Description Repository
        run: mvn test -f "basyx.conceptdescriptionrepository/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-submodelregistry:
    runs-on: ubuntu-latest
    name: Test BaSyx Submodel Registry
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test Submodel Registry
        run: mvn test -f "basyx.submodelregistry/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-aasregistry:
    runs-on: ubuntu-latest
    name: Test BaSyx AAS Registry
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test AAS Registry
        run: mvn test -f "basyx.aasregistry/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down
  test-basyx-aasdiscoveryservice:
    runs-on: ubuntu-latest
    name: Test BaSyx AAS Discovery Service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Start environment
        run: docker compose --project-directory ./ci up -d --wait
      - name: Build BaSyx
        run: mvn clean install ${MVN_ARGS_BUILD_BASYX_NO_TESTS}
      - name: Test AAS Discovery Service
        run: mvn test -f "basyx.aasdiscoveryservice/pom.xml"
      - name: Stop environment
        if: always()
        run: docker compose --project-directory ./ci down