name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CODING_CONVENTIONS.md'
      - '.github/CONTRIBUTING.md'
      - '.github/dependabot.yml'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build and remove Docker images
        run: |
          images=(submodelrepository, aasrepository, aasenvironment, conceptdescriptionrepository, aasdiscoveryservice, aasxfileserver)
          registryimages=(aasregistry-service-release-kafka-mem, aasregistry-service-release-kafka-mongodb, aasregistry-service-release-log-mem, aasregistry-service-release-log-mongodb, basyx.submodelregistry-service-release-log-mongodb, submodelregistry-service-release-log-mem, submodelregistry-service-release-kafka-mongodb, submodelregistry-service-release-kafka-mem)
          for image in "${images[@]}"; do
            mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.$image.component"
            docker rm -vf $(docker ps -aq)
            docker rmi -f $(docker images -aq)
          done
          for image in "${registryimages[@]}"; do
            mvn package -DskipTests -Ddocker.namespace=test --pl "org.eclipse.digitaltwin.basyx:basyx.$image"
            docker rm -vf $(docker ps -aq)
            docker rmi -f $(docker images -aq)
          done
